version: '3.8'

name: gestion-app-container

services:
  app:
    image: greciadelgado/gestion-app:latest
    container_name: gestion-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: gestion-app-network